minecraft_version=1.18.2
java_version=17
forge_version=40.2.27
moddev_version=2.0.141
plugin_id=net.neoforged.moddev.legacyforge
common_project=common-1.18.2
merge_common_sources=true
glue_source_dir=forge/1.18.2/src/main/java
patchouli_version=
loader_version_range=[40,)
minecraft_version_range=[1.18.2]
forge_version_range=[40,)
