minecraft_version=1.20.1
java_version=17
forge_version=47.3.0
moddev_version=2.0.141
plugin_id=net.neoforged.moddev.legacyforge
common_project=common-1.20.1
merge_common_sources=true
glue_source_dir=forge/1.20.1/src/main/java
patchouli_version=
loader_version_range=[47,)
minecraft_version_range=[1.20.1]
forge_version_range=[47,)
