minecraft_version=1.20.1
java_version=17
loader_version=0.15.11
fabric_api_version=0.92.2+1.20.1
fabric_api_mod_id=fabric-api
mappings_type=official
patchouli_version=1.20.1-84-FABRIC
loom_version=1.11.8
common_project=common-1.20.1
merge_common_sources=true
glue_source_dir=fabric/1.20.1/src/main/java
