minecraft_version=1.21.8
java_version=21
loader_version=0.16.14
fabric_api_version=0.130.0+1.21.8
fabric_api_mod_id=fabric-api
mappings_type=official
patchouli_version=
loom_version=1.11.8
common_project=common-1.21.8
merge_common_sources=true
glue_source_dir=fabric/1.21.8/src/main/java
