minecraft_version=26.1
java_version=25
loader_version=0.19.3
fabric_api_version=0.145.1+26.1
fabric_api_mod_id=fabric-api
mappings_type=none
patchouli_version=
use_mod_deps=false
loom_version=1.17-SNAPSHOT
loom_plugin_id=net.fabricmc.fabric-loom
common_project=common-26.1
merge_common_sources=true
glue_source_dir=fabric/26.1/src/main/java
