minecraft_version=1.21.8
java_version=21
neoforge_version=21.8.53
moddev_version=2.0.141
plugin_id=net.neoforged.moddev
common_project=common-1.21.8
merge_common_sources=true
use_jarjar_common=false
glue_source_dir=neoforge/1.21.8/src/main/java
patchouli_version=
loader_version_range=[4,)
minecraft_version_range=[1.21.8]
neoforge_version_range=[21.8.53,)
