minecraft_version=26.1
java_version=25
neoforge_version=26.1.0.19-beta
moddev_version=2.0.141
plugin_id=net.neoforged.moddev
common_project=common-26.1
merge_common_sources=true
merge_guide_book_client=false
use_jarjar_common=false
glue_source_dir=neoforge/26.1/src/main/java
patchouli_version=
loader_version_range=[4,)
minecraft_version_range=[26.1]
neoforge_version_range=[26.1.0.19-beta,)
