[progression]
	xpCurveBase = 50.0
	xpExponentBase = 0.15
	xpExponentPerLevel = 0.01
	xpRequiredMultiplier = 1.0
	globalXpGainMultiplier = 1.0
	miningXpGainMultiplier = 1.0
	combatXpGainMultiplier = 1.0
	swordXpPaceDivisor = 1.2
	hoeXpPaceDivisor = 5.0
	bowXpPaceDivisor = 1.2
	shieldXpPaceDivisor = 4.0

[shield]
	blockChanceMin = 0.50
	blockChanceMax = 0.99

[armor]
	wearXpInterval = 400

[client]
	tierParticlesEnabled = true
